# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 17:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed', models.FloatField(blank=True, default=None, null=True)),
                ('time', models.BigIntegerField()),
                ('accuracy', models.FloatField(blank=True, default=None, null=True)),
                ('battery', models.FloatField(blank=True, default=None, null=True)),
                ('provider', models.CharField(blank=True, default=None, max_length=50)),
                ('bearing', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
