# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour_config', '0001_initial'),
        ('rider', '0001_initial'),
        ('location_update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.Rider'),
        ),
        migrations.AddField(
            model_name='location',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour_config.TourConfig', to_field=b'tour_id'),
        ),
    ]
